### ISSUE TITLE
403 Cloudflare error code on authentication

### ISSUE THREAD

**Issue by wawawaaw** [KebsCS/LeagueClientDebugger#1]
Hello, since the new Vanguard update, neither launching the game with modified LeagueClient with HxD nor with your application works, do you have any solution for this?

**Comment by Memelord187** [comment]
![image](https://github.com/KebsCS/LeagueClientDebugger/assets/152624375/6f06642a-e7b5-4bb0-8a4e-09e57f824d26)

Im also unable to login, keeps saying "Sorry, were having trouble signing you in right now. Please try again later"

**Comment by KebsCS** [comment]
I couldn't reproduce the issue since this part fixes 403s for me https://github.com/KebsCS/LeagueClientDebugger/blob/main/LeagueClientDebugger/HttpProxy.py#L25

I've uploaded a new commit that fixed the same problem when I was using proxies. Maybe that'll help. If not, you can disable the auth proxy in Tools -> Options. It'll no longer capture login requests, but I think it should be fine for everything else

**Comment by Memelord187** [comment]
Disabling auth capture fixes the issue for me

**Comment by wawawaaw** [comment]
> I couldn't reproduce the issue since this part fixes 403s for me https://github.com/KebsCS/LeagueClientDebugger/blob/main/LeagueClientDebugger/HttpProxy.py#L25
> 
> I've uploaded a new commit that fixed the same problem when I was using proxies. Maybe that'll help. If not, you can disable the auth proxy in Tools -> Options. It'll no longer capture login requests, but I think it should be fine for everything else

Thanks login is now working

**Comment by 70805** [comment]
Whether it is possible to publish a compiled version

**Comment by KebsCS** [comment]
Is this error still happening on the latest commit if the auth proxy is not disabled in Tools -> Options?
